import * as esbuild from 'esbuild';
import { resolve, dirname, basename } from 'path';
import { fileURLToPath } from 'url';
import { readFileSync, writeFileSync, readdirSync, unlinkSync, mkdirSync, existsSync } from 'fs';
import { createHash } from 'crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const watch = process.argv.includes('--watch');

// Build-time version stamp. Same value gets baked into each client bundle via
// esbuild define AND written to app/<role>/dist/build-version.txt so the server
// can read it on startup. Clients compare the baked value against /sw-version.json
// to detect stale installs.
const BUILD_VERSION = process.env.GC_BUILD_VERSION
  || process.env.GC_BUILD_ID
  || `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

const sharedConfig = {
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2022'],
  sourcemap: true,
  minify: !watch,
  jsx: 'automatic',
  jsxImportSource: 'preact',
  loader: { '.ts': 'ts', '.tsx': 'tsx' },
  alias: {
    'react': 'preact/compat',
    'react-dom': 'preact/compat',
    '@gloomhaven-command/shared': resolve(__dirname, '../packages/shared/src/index.ts'),
  },
  define: {
    'process.env.GC_BUILD_VERSION': JSON.stringify(BUILD_VERSION),
  },
  logLevel: 'info',
};

const entryPoints = [
  { name: 'controller', entry: 'controller/main.tsx' },
  { name: 'phone',      entry: 'phone/main.tsx' },
  { name: 'display',    entry: 'display/main.tsx' },
];

// CSS files included in service worker precache per role (roles with SWs only)
const SW_CSS = {
  controller: [
    '/app/shared/styles/theme.css',
    '/app/shared/styles/typography.css',
    '/app/shared/styles/components.css',
    '/app/shared/styles/connection.css',
    '/app/shared/styles/sheets.css',
    '/app/controller/styles/controller.css',
  ],
  phone: [
    '/app/shared/styles/theme.css',
    '/app/shared/styles/typography.css',
    '/app/shared/styles/components.css',
    '/app/shared/styles/connection.css',
    '/app/shared/styles/sheets.css',
    '/app/phone/styles/phone.css',
  ],
  display: [
    '/app/shared/styles/theme.css',
    '/app/shared/styles/typography.css',
    '/app/shared/styles/components.css',
    '/app/shared/styles/connection.css',
    '/app/display/styles/display.css',
  ],
};

// ── Helpers ──────────────────────────────────────────────────────────────────

function hashFileContents(filePaths) {
  const h = createHash('sha256');
  for (const fp of filePaths) h.update(readFileSync(fp));
  return h.digest('hex').slice(0, 10);
}

function cleanDist(distDir) {
  if (!existsSync(distDir)) return;
  for (const f of readdirSync(distDir)) {
    if (/^main.*\.(js|js\.map)$/.test(f) || f === 'index.html' || f === 'sw.js') {
      unlinkSync(resolve(distDir, f));
    }
  }
}

function generateHtml(role, hashedJsFilename) {
  const src = readFileSync(resolve(__dirname, role, 'index.html'), 'utf-8');
  return src.replace(
    `src="/app/${role}/dist/main.js"`,
    `src="/app/${role}/dist/${hashedJsFilename}"`,
  );
}

/**
 * Generate the self-healing SW. Network-first for all previewable traffic,
 * cache fallback for offline. On activate, pings /sw-version.json and
 * self-destructs if the server version differs. Bypass list protects the
 * escape-hatch routes from ever being intercepted.
 */
function generateSw(role, hashedJsFilename, cacheName, scope) {
  const cssUrls = SW_CSS[role];
  if (!cssUrls) return null;

  const urls = [
    `'/${role}'`,
    ...cssUrls.map(u => `'${u}'`),
    `'/app/${role}/dist/${hashedJsFilename}'`,
  ];

  return `// Generated by app/build.mjs — self-healing service worker.
// SW_VERSION is pinned into CACHE_NAME at build time, and injected at request
// time by the server so the activate-time version check matches the live server.
const SW_VERSION = self.GC_SW_VERSION_INJECTED || ${JSON.stringify(cacheName)};
const CACHE_NAME = 'gc-${role}-' + SW_VERSION;
const SCOPE_ROOT = ${JSON.stringify(scope)};
const APP_SHELL = [
  ${urls.join(',\n  ')},
];

// Paths the SW must NEVER intercept — escape hatches and non-cacheable data.
const BYPASS_PATHS = ['/api/', '/assets/', '/sw-version.json', '/unregister'];

function isBypassed(url) {
  if (BYPASS_PATHS.some((p) => url.pathname.startsWith(p))) return true;
  if (url.pathname.endsWith('/sw.js')) return true;
  return false;
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(APP_SHELL))
      .catch((err) => { console.warn('[sw] Install addAll failed, continuing:', err); })
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)));
    await self.clients.claim();
    try {
      const res = await fetch('/sw-version.json', { cache: 'no-store' });
      if (res.ok) {
        const body = await res.json();
        if (body && body.version && body.version !== SW_VERSION) {
          console.warn('[sw] Version mismatch on activate, self-destructing',
            { sw: SW_VERSION, server: body.version });
          await selfDestruct();
        }
      }
    } catch (_) { /* offline — don't self-destruct */ }
  })());
});

async function selfDestruct() {
  try {
    const keys = await caches.keys();
    await Promise.all(keys.map((k) => caches.delete(k)));
  } catch (_) { /* ignore */ }
  try {
    const reg = await self.registration;
    if (reg) await reg.unregister();
  } catch (_) { /* ignore */ }
  try {
    const all = await self.clients.matchAll();
    for (const c of all) { try { c.postMessage({ type: 'sw-self-destructed' }); } catch (_) {} }
  } catch (_) { /* ignore */ }
}

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (isBypassed(url)) return;

  const isNavigate = event.request.mode === 'navigate'
    || (event.request.method === 'GET'
        && (event.request.headers.get('accept') || '').includes('text/html'));

  if (isNavigate) {
    event.respondWith((async () => {
      try {
        const response = await fetch(event.request);
        if (response && response.status === 200) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone)).catch(() => {});
        }
        return response;
      } catch (_) {
        const cached = await caches.match(event.request);
        if (cached) return cached;
        const fallback = await caches.match(SCOPE_ROOT);
        if (fallback) return fallback;
        return Response.error();
      }
    })());
    return;
  }

  // Static assets: network-first with cache fallback.
  event.respondWith((async () => {
    try {
      const response = await fetch(event.request);
      if (event.request.method === 'GET' && response && response.status === 200) {
        const clone = response.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone)).catch(() => {});
      }
      return response;
    } catch (_) {
      const cached = await caches.match(event.request);
      if (cached) return cached;
      return Response.error();
    }
  })());
});
`;
}

// ── Build ────────────────────────────────────────────────────────────────────

async function build() {
  for (const ep of entryPoints) {
    const distDir = resolve(__dirname, ep.name, 'dist');
    mkdirSync(distDir, { recursive: true });

    // Always write the build version so the server can read it on startup.
    writeFileSync(resolve(distDir, 'build-version.txt'), BUILD_VERSION);

    if (watch) {
      // Dev mode: plain filenames, source HTML/SW used as-is
      const ctx = await esbuild.context({
        ...sharedConfig,
        entryPoints: [resolve(__dirname, ep.entry)],
        outfile: resolve(distDir, 'main.js'),
      });
      await ctx.watch();
      console.log(`Watching ${ep.name}...`);
    } else {
      // Production: content-hashed filenames + generated HTML/SW
      cleanDist(distDir);

      const result = await esbuild.build({
        ...sharedConfig,
        entryPoints: [resolve(__dirname, ep.entry)],
        outdir: distDir,
        entryNames: '[name]-[hash]',
        metafile: true,
      });

      // Extract hashed filename from metafile
      const jsOutput = Object.keys(result.metafile.outputs)
        .find(o => o.endsWith('.js') && !o.endsWith('.js.map'));
      const hashedFilename = basename(jsOutput);
      console.log(`Built ${ep.name} → ${hashedFilename}`);

      // Generate dist/index.html with hashed script reference
      writeFileSync(resolve(distDir, 'index.html'), generateHtml(ep.name, hashedFilename));
      console.log(`  Generated ${ep.name}/dist/index.html`);

      // Generate dist/sw.js (if role has a SW)
      if (SW_CSS[ep.name]) {
        const cssFiles = SW_CSS[ep.name].map(u => resolve(__dirname, u.replace(/^\/app\//, '')));
        const contentHash = hashFileContents([...cssFiles, resolve(distDir, hashedFilename)]);
        // Fallback cache-name seed if the server never injects SW_VERSION (e.g.,
        // SW loaded off-origin/offline during a rare edge case).
        const fallbackVersion = `${BUILD_VERSION}-${contentHash}`;
        writeFileSync(
          resolve(distDir, 'sw.js'),
          generateSw(ep.name, hashedFilename, fallbackVersion, `/${ep.name}`),
        );
        console.log(`  Generated ${ep.name}/dist/sw.js (fallback SW_VERSION: ${fallbackVersion})`);
      }
    }
  }

  console.log(`GC_BUILD_VERSION=${BUILD_VERSION}`);
}

build().catch(err => { console.error(err); process.exit(1); });
